### ISSUE TITLE
Unable to access key feature:

### ISSUE THREAD

**Issue by denniskline** [RobertStevenson/chocolate-peanut-butter#1]
![choc-peanutbutter-piejpg](https://cloud.githubusercontent.com/assets/4529833/25752112/45dcd702-3185-11e7-8a1c-25d357b6f21f.jpg)

**Comment by RobertStevenson** [comment]
Thank you so much for your issue. Our top-notch development team is considering adding this into a future release, but behind a pay-wall due to your obvious willingness to pay for it.

**Comment by ChrisBarthol** [comment]
+1
